sprint2rest:
    resource: "@sprint2restBundle/Resources/config/routing.yml"
    prefix:   /

sprint2_real_estate_admin:
    resource: "@sprint2RealEstateAdminBundle/Resources/config/routing.yml"
    prefix:   /

real_estate:
    resource: "@realEstateBundle/Resources/config/routing.yml"
    prefix:   /
    
real_estate_authentification:
    resource: "@sprint2AuthandlogBundle/Resources/config/routing.yml"
    prefix:   /
    
sprint2_gerant:
    resource: "@sprint2GerantBundle/Resources/config/routing.yml"
    prefix:   /gerant

real_estate_admin:
    resource: "@sprint2RealEstateAdminBundle/Resources/config/routing.yml"
    prefix:   /Admin
    
app:
    resource: @AppBundle/Controller/
    type:     annotation

sprint2rest:
    resource: "@sprint2restBundle/Resources/config/routing.yml"
    prefix:   /api
    type: rest
